// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hateekub.Data;

#nullable disable

namespace hateekub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304153202_AddProfileImage")]
    partial class AddProfileImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("hateekub.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameName = "CS2",
                            GameType = "FPS",
                            MaxPlayers = 5,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 2,
                            GameName = "Valorant",
                            GameType = "FPS",
                            MaxPlayers = 5,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 3,
                            GameName = "Overwatch",
                            GameType = "FPS",
                            MaxPlayers = 5,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 4,
                            GameName = "LoL",
                            GameType = "MOBA",
                            MaxPlayers = 5,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 5,
                            GameName = "Mobile Legends",
                            GameType = "MOBA",
                            MaxPlayers = 5,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 6,
                            GameName = "RoV",
                            GameType = "MOBA",
                            MaxPlayers = 5,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 7,
                            GameName = "Among Us",
                            GameType = "Party",
                            MaxPlayers = 15,
                            MinPlayers = 4
                        },
                        new
                        {
                            Id = 8,
                            GameName = "Peak",
                            GameType = "Party",
                            MaxPlayers = 4,
                            MinPlayers = 1
                        },
                        new
                        {
                            Id = 9,
                            GameName = "PUBG",
                            GameType = "Battle Royale",
                            MaxPlayers = 4,
                            MinPlayers = 1
                        });
                });

            modelBuilder.Entity("hateekub.Models.GameRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("RankImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameRanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Iron.webp",
                            RankName = "Iron"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Bronze.webp",
                            RankName = "Bronze"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Silver.webp",
                            RankName = "Silver"
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Gold.webp",
                            RankName = "Gold"
                        },
                        new
                        {
                            Id = 5,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Platinum.webp",
                            RankName = "Platinum"
                        },
                        new
                        {
                            Id = 6,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Diamond.webp",
                            RankName = "Diamond"
                        },
                        new
                        {
                            Id = 7,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Immortal.webp",
                            RankName = "Immortal"
                        },
                        new
                        {
                            Id = 8,
                            GameId = 2,
                            RankImageUrl = "/images/ranks/val/Radiant.webp",
                            RankName = "Radiant"
                        },
                        new
                        {
                            Id = 9,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Iron.webp",
                            RankName = "Warrior"
                        },
                        new
                        {
                            Id = 10,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Elite.webp",
                            RankName = "Elite"
                        },
                        new
                        {
                            Id = 11,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Master.webp",
                            RankName = "Master"
                        },
                        new
                        {
                            Id = 12,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Grandmaster.webp",
                            RankName = "Grandmaster"
                        },
                        new
                        {
                            Id = 13,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Epic.webp",
                            RankName = "Epic"
                        },
                        new
                        {
                            Id = 14,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Legend.webp",
                            RankName = "Legend"
                        },
                        new
                        {
                            Id = 15,
                            GameId = 5,
                            RankImageUrl = "/images/ranks/mlbb/Mythic.webp",
                            RankName = "Mythic"
                        },
                        new
                        {
                            Id = 16,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Bronze.webp",
                            RankName = "Bronze"
                        },
                        new
                        {
                            Id = 17,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Silver.webp",
                            RankName = "Silver"
                        },
                        new
                        {
                            Id = 18,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Gold.webp",
                            RankName = "Gold"
                        },
                        new
                        {
                            Id = 19,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Platinum.webp",
                            RankName = "Platinum"
                        },
                        new
                        {
                            Id = 20,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Diamond.webp",
                            RankName = "Diamond"
                        },
                        new
                        {
                            Id = 21,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Master.webp",
                            RankName = "Master"
                        },
                        new
                        {
                            Id = 22,
                            GameId = 3,
                            RankImageUrl = "/images/ranks/Ow2/Grandmaster.webp",
                            RankName = "Grandmaster"
                        },
                        new
                        {
                            Id = 23,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Unranked.webp",
                            RankName = "Unranked"
                        },
                        new
                        {
                            Id = 24,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Iron.webp",
                            RankName = "Iron"
                        },
                        new
                        {
                            Id = 25,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Bronze.webp",
                            RankName = "Bronze"
                        },
                        new
                        {
                            Id = 26,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Silver.webp",
                            RankName = "Silver"
                        },
                        new
                        {
                            Id = 27,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Gold.webp",
                            RankName = "Gold"
                        },
                        new
                        {
                            Id = 28,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Platinum.webp",
                            RankName = "Platinum"
                        },
                        new
                        {
                            Id = 29,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Emerald.webp",
                            RankName = "Emerald"
                        },
                        new
                        {
                            Id = 30,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Diamond.webp",
                            RankName = "Diamond"
                        },
                        new
                        {
                            Id = 31,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Master.webp",
                            RankName = "Master"
                        },
                        new
                        {
                            Id = 32,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Grandmaster.webp",
                            RankName = "Grandmaster"
                        },
                        new
                        {
                            Id = 33,
                            GameId = 4,
                            RankImageUrl = "/images/ranks/LoL/Challenger.webp",
                            RankName = "Challenger"
                        },
                        new
                        {
                            Id = 34,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Bronze.webp",
                            RankName = "Bronze"
                        },
                        new
                        {
                            Id = 35,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Silver.webp",
                            RankName = "Silver"
                        },
                        new
                        {
                            Id = 36,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Gold.webp",
                            RankName = "Gold"
                        },
                        new
                        {
                            Id = 37,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Platinum.webp",
                            RankName = "Platinum"
                        },
                        new
                        {
                            Id = 38,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Crown.webp",
                            RankName = "Crown"
                        },
                        new
                        {
                            Id = 39,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Ace.webp",
                            RankName = "Ace"
                        },
                        new
                        {
                            Id = 40,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/AceMaster.webp",
                            RankName = "AceMaster"
                        },
                        new
                        {
                            Id = 41,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/AceDominator.webp",
                            RankName = "AceDominator"
                        },
                        new
                        {
                            Id = 42,
                            GameId = 9,
                            RankImageUrl = "/images/ranks/Pubg/Conqueror.webp",
                            RankName = "Conqueror"
                        });
                });

            modelBuilder.Entity("hateekub.Models.GameRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 2,
                            RoleName = "Duelist"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 2,
                            RoleName = "Controller"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            RoleName = "Initiator"
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            RoleName = "Sentinel"
                        },
                        new
                        {
                            Id = 5,
                            GameId = 4,
                            RoleName = "Top Lane"
                        },
                        new
                        {
                            Id = 6,
                            GameId = 4,
                            RoleName = "Jungle"
                        },
                        new
                        {
                            Id = 7,
                            GameId = 4,
                            RoleName = "Mid Lane"
                        },
                        new
                        {
                            Id = 8,
                            GameId = 4,
                            RoleName = "ADC"
                        },
                        new
                        {
                            Id = 9,
                            GameId = 4,
                            RoleName = "Support"
                        },
                        new
                        {
                            Id = 10,
                            GameId = 6,
                            RoleName = "Top Lane"
                        },
                        new
                        {
                            Id = 11,
                            GameId = 6,
                            RoleName = "Jungle"
                        },
                        new
                        {
                            Id = 12,
                            GameId = 6,
                            RoleName = "Mid Lane"
                        },
                        new
                        {
                            Id = 13,
                            GameId = 6,
                            RoleName = "ADC"
                        },
                        new
                        {
                            Id = 14,
                            GameId = 6,
                            RoleName = "Support"
                        },
                        new
                        {
                            Id = 15,
                            GameId = 3,
                            RoleName = "Tank"
                        },
                        new
                        {
                            Id = 16,
                            GameId = 3,
                            RoleName = "Damage"
                        },
                        new
                        {
                            Id = 17,
                            GameId = 3,
                            RoleName = "Support"
                        });
                });

            modelBuilder.Entity("hateekub.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("hateekub.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("hateekub.Models.ProfileGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ProfileGames");
                });

            modelBuilder.Entity("hateekub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("hateekub.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("hateekub.Models.RoomChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomChats");
                });

            modelBuilder.Entity("hateekub.Models.RoomPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RankId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomPlayers");
                });

            modelBuilder.Entity("hateekub.Models.RoomQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomQueues");
                });

            modelBuilder.Entity("hateekub.Models.RoomSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDuplicateRole")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayer")
                        .HasColumnType("integer");

                    b.Property<string>("MaxRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomSettings");
                });

            modelBuilder.Entity("hateekub.Models.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtraDataJson")
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("InGameName")
                        .HasColumnType("text");

                    b.Property<int?>("RankDivision")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RankLastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RankTier")
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserProfileId", "GameId")
                        .IsUnique();

                    b.ToTable("UserGames");
                });

            modelBuilder.Entity("hateekub.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hateekub.Models.GameRank", b =>
                {
                    b.HasOne("hateekub.Models.Game", "Game")
                        .WithMany("GameRanks")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("hateekub.Models.GameRole", b =>
                {
                    b.HasOne("hateekub.Models.Game", "Game")
                        .WithMany("GameRoles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("hateekub.Models.History", b =>
                {
                    b.HasOne("hateekub.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "User")
                        .WithMany("Histories")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hateekub.Models.Notification", b =>
                {
                    b.HasOne("hateekub.Models.UserProfile", "UserProfile")
                        .WithMany("Notifications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("hateekub.Models.ProfileGame", b =>
                {
                    b.HasOne("hateekub.Models.UserProfile", "UserProfile")
                        .WithMany("ProfileGames")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("hateekub.Models.Review", b =>
                {
                    b.HasOne("hateekub.Models.UserProfile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hateekub.Models.Room", b =>
                {
                    b.HasOne("hateekub.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "RoomOwner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("RoomOwner");
                });

            modelBuilder.Entity("hateekub.Models.RoomChat", b =>
                {
                    b.HasOne("hateekub.Models.Room", "Room")
                        .WithMany("Chats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hateekub.Models.RoomPlayer", b =>
                {
                    b.HasOne("hateekub.Models.GameRank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId");

                    b.HasOne("hateekub.Models.GameRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("hateekub.Models.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("Role");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hateekub.Models.RoomQueue", b =>
                {
                    b.HasOne("hateekub.Models.Room", "Room")
                        .WithMany("QueuePlayers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hateekub.Models.RoomSetting", b =>
                {
                    b.HasOne("hateekub.Models.Room", "Room")
                        .WithOne("RoomSetting")
                        .HasForeignKey("hateekub.Models.RoomSetting", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("hateekub.Models.UserGame", b =>
                {
                    b.HasOne("hateekub.Models.Game", "Game")
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hateekub.Models.UserProfile", "User")
                        .WithMany("UserGames")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hateekub.Models.Game", b =>
                {
                    b.Navigation("GameRanks");

                    b.Navigation("GameRoles");

                    b.Navigation("UserGames");
                });

            modelBuilder.Entity("hateekub.Models.Room", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Players");

                    b.Navigation("QueuePlayers");

                    b.Navigation("RoomSetting");
                });

            modelBuilder.Entity("hateekub.Models.UserProfile", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Notifications");

                    b.Navigation("ProfileGames");

                    b.Navigation("Reviews");

                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
